/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package test;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import mijzcx.synapse.desk.utils.CloseDialog;
import mijzcx.synapse.desk.utils.KeyMapping;
import mijzcx.synapse.desk.utils.KeyMapping.KeyAction;





/**
 *
 * @author Dummy
 */
public class Dlg_menus_su_cashier extends javax.swing.JDialog {

    /** Creates new form Dlg_menus */
    //<editor-fold defaultstate="collapsed" desc=" callback ">
    private Callback callback;

    public void setCallback(Callback callback) {
        this.callback = callback;


}

    public static interface Callback {

    void ok(CloseDialog closeDialog, OutputData data);
}

public static class InputData {
}

public static class OutputData {
}
//</editor-fold>
 
    //<editor-fold defaultstate="collapsed" desc=" Constructors ">
private Dlg_menus_su_cashier(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        myInit();
    }

    private Dlg_menus_su_cashier(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        myInit();
    }

    public Dlg_menus_su_cashier() {
        super();
        initComponents();
        myInit();

    }
    private Dlg_menus_su_cashier myRef;

    private void setThisRef(Dlg_menus_su_cashier myRef) {
        this.myRef = myRef;
    }
    private static java.util.Map<Object, Dlg_menus_su_cashier> dialogContainer = new java.util.HashMap();

    public static void clearUpFirst(java.awt.Window parent) {
        if (dialogContainer.containsKey(parent)) {
            dialogContainer.remove(parent);
        }
    }

    public static Dlg_menus_su_cashier create(java.awt.Window parent, boolean modal) {

        if (modal) {
            return create(parent, ModalityType.APPLICATION_MODAL);
        }

        return create(parent, ModalityType.MODELESS);

    }

    public static Dlg_menus_su_cashier create(java.awt.Window parent, java.awt.Dialog.ModalityType modalType) {

        if (parent instanceof java.awt.Frame) {

            Dlg_menus_su_cashier dialog = dialogContainer.get(parent);

            if (dialog == null) {
                dialog = new Dlg_menus_su_cashier((java.awt.Frame) parent, false);
                dialog.setModalityType(modalType);
                dialogContainer.put(parent, dialog);
                java.util.logging.Logger.getAnonymousLogger().log(Level.INFO, "instances: {0}", dialogContainer.size());
                dialog.setThisRef(dialog);
                return dialog;
            } else {
                dialog.setModalityType(modalType);
                return dialog;
            }

        }

        if (parent instanceof java.awt.Dialog) {
            Dlg_menus_su_cashier dialog = dialogContainer.get(parent);

            if (dialog == null) {
                dialog = new Dlg_menus_su_cashier((java.awt.Dialog) parent, false);
                dialog.setModalityType(modalType);
                dialogContainer.put(parent, dialog);
                java.util.logging.Logger.getAnonymousLogger().log(Level.INFO, "instances: {0}", dialogContainer.size());
                dialog.setThisRef(dialog);
                return dialog;
            } else {
                dialog.setModalityType(modalType);
                return dialog;
            }

        }

        return null;

    }
    //</editor-fold>    

    //<editor-fold defaultstate="collapsed" desc=" main ">
    public static void main(String args[]) {

        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            throw new RuntimeException(e);
        }


        Dlg_menus_su_cashier dialog = Dlg_menus_su_cashier.create(new javax.swing.JFrame(), true);
        dialog.setVisible(true);

    }
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc=" added ">
    @Override
        public void setVisible(boolean visible) {
        super.setVisible(visible);
        if (visible == true) {
            getContentPane().removeAll();
            initComponents();
            myInit();
            repaint();
        }


    }

    public javax.swing.JPanel getSurface() {
        return (javax.swing.JPanel) getContentPane();
    }

    public void nullify() {
        myRef.setVisible(false);
        myRef = null;
    }
    //</editor-fold>

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_logout = new javax.swing.JButton();
        btn_standby = new javax.swing.JButton();
        lb_standby = new javax.swing.JLabel();
        lb_logout = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lb_pen = new javax.swing.JLabel();
        btn_pending = new javax.swing.JButton();
        lb_pending = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img2/log-out2.png"))); // NOI18N
        btn_logout.setBorderPainted(false);
        btn_logout.setContentAreaFilled(false);
        btn_logout.setFocusable(false);
        btn_logout.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img2/log-out button-MO.png"))); // NOI18N
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 110, -1));

        btn_standby.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img2/stand-by.png"))); // NOI18N
        btn_standby.setBorderPainted(false);
        btn_standby.setContentAreaFilled(false);
        btn_standby.setFocusable(false);
        btn_standby.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img2/stand-by-MO.png"))); // NOI18N
        btn_standby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_standbyActionPerformed(evt);
            }
        });
        getContentPane().add(btn_standby, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, -1, 70));

        lb_standby.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        lb_standby.setForeground(new java.awt.Color(41, 9, 149));
        lb_standby.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_standby.setText("STANDBY");
        lb_standby.setFocusable(false);
        getContentPane().add(lb_standby, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, 100, 20));

        lb_logout.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        lb_logout.setForeground(new java.awt.Color(41, 9, 149));
        lb_logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_logout.setText("LOGOUT");
        lb_logout.setFocusable(false);
        getContentPane().add(lb_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 80, 110, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, 90, 100));

        lb_pen.setBackground(new java.awt.Color(251, 200, 213));
        lb_pen.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lb_pen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_pen.setText("5");
        lb_pen.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lb_pen.setFocusable(false);
        lb_pen.setOpaque(true);
        getContentPane().add(lb_pen, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 30, 30));

        btn_pending.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img2/pending.png"))); // NOI18N
        btn_pending.setBorderPainted(false);
        btn_pending.setContentAreaFilled(false);
        btn_pending.setFocusable(false);
        btn_pending.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/POS/img2/pending-MO.png"))); // NOI18N
        btn_pending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pendingActionPerformed(evt);
            }
        });
        getContentPane().add(btn_pending, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        lb_pending.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        lb_pending.setForeground(new java.awt.Color(41, 9, 149));
        lb_pending.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_pending.setText("PENDING");
        lb_pending.setFocusable(false);
        getContentPane().add(lb_pending, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
//        log_out();
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_standbyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_standbyActionPerformed
//        do_login("");
    }//GEN-LAST:event_btn_standbyActionPerformed

    private void btn_pendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pendingActionPerformed
//        do_show_pending();
    }//GEN-LAST:event_btn_pendingActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_pending;
    private javax.swing.JButton btn_standby;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_logout;
    private javax.swing.JLabel lb_pen;
    private javax.swing.JLabel lb_pending;
    private javax.swing.JLabel lb_standby;
    // End of variables declaration//GEN-END:variables

    private void myInit() {
        init_key();
    }

    public void do_pass(){
 
    }
    // <editor-fold defaultstate="collapsed" desc="Key">
    private void disposed() {
        this.dispose();
    }

    private void init_key() {
        KeyMapping.mapKeyWIFW(getSurface(),
                KeyEvent.VK_ESCAPE, new KeyAction() {
            
            @Override
        public void actionPerformed(ActionEvent e) {
//                btn_0.doClick();
                disposed();
            }
        });
    }
    // </editor-fold>
    
    
}
