/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import mijzcx.synapse.desk.utils.CloseDialog;
import mijzcx.synapse.desk.utils.KeyMapping;
import mijzcx.synapse.desk.utils.KeyMapping.KeyAction;

/**
 *
 * @author Dummy
 */
public class Dlg_table_type extends javax.swing.JDialog {

    /**
     * Creates new form Dlg_table_type
     */
    //<editor-fold defaultstate="collapsed" desc=" callback ">
    private Callback callback;

    public void setCallback(Callback callback) {
        this.callback = callback;


    }

    public static interface Callback {

        void ok(CloseDialog closeDialog, OutputData data);
    }

    public static class InputData {
    }

    public static class OutputData {
    }
//</editor-fold>

    //<editor-fold defaultstate="collapsed" desc=" Constructors ">
    private Dlg_table_type(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        myInit();
    }

    private Dlg_table_type(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        myInit();
    }

    public Dlg_table_type() {
        super();
        initComponents();
        myInit();

    }
    private Dlg_table_type myRef;

    private void setThisRef(Dlg_table_type myRef) {
        this.myRef = myRef;
    }
    private static java.util.Map<Object, Dlg_table_type> dialogContainer = new java.util.HashMap();

    public static void clearUpFirst(java.awt.Window parent) {
        if (dialogContainer.containsKey(parent)) {
            dialogContainer.remove(parent);
        }
    }

    public static Dlg_table_type create(java.awt.Window parent, boolean modal) {

        if (modal) {
            return create(parent, ModalityType.APPLICATION_MODAL);
        }

        return create(parent, ModalityType.MODELESS);

    }

    public static Dlg_table_type create(java.awt.Window parent, java.awt.Dialog.ModalityType modalType) {

        if (parent instanceof java.awt.Frame) {

            Dlg_table_type dialog = dialogContainer.get(parent);

            if (dialog == null) {
                dialog = new Dlg_table_type((java.awt.Frame) parent, false);
                dialog.setModalityType(modalType);
                dialogContainer.put(parent, dialog);
                java.util.logging.Logger.getAnonymousLogger().log(Level.INFO, "instances: {0}", dialogContainer.size());
                dialog.setThisRef(dialog);
                return dialog;
            } else {
                dialog.setModalityType(modalType);
                return dialog;
            }

        }

        if (parent instanceof java.awt.Dialog) {
            Dlg_table_type dialog = dialogContainer.get(parent);

            if (dialog == null) {
                dialog = new Dlg_table_type((java.awt.Dialog) parent, false);
                dialog.setModalityType(modalType);
                dialogContainer.put(parent, dialog);
                java.util.logging.Logger.getAnonymousLogger().log(Level.INFO, "instances: {0}", dialogContainer.size());
                dialog.setThisRef(dialog);
                return dialog;
            } else {
                dialog.setModalityType(modalType);
                return dialog;
            }

        }

        return null;

    }
    //</editor-fold>    

    //<editor-fold defaultstate="collapsed" desc=" main ">
    public static void main(String args[]) {

        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            throw new RuntimeException(e);
        }


        Dlg_table_type dialog = Dlg_table_type.create(new javax.swing.JFrame(), true);
        dialog.setVisible(true);

    }
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc=" added ">
    @Override
    public void setVisible(boolean visible) {
        super.setVisible(visible);
        if (visible == true) {
            getContentPane().removeAll();
            initComponents();
            myInit();
            repaint();
        }


    }

    public javax.swing.JPanel getSurface() {
        return (javax.swing.JPanel) getContentPane();
    }

    public void nullify() {
        myRef.setVisible(false);
        myRef = null;
    }
    //</editor-fold>

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_price = new org.jdesktop.swingx.JXLabel();
        lbl_desc = new org.jdesktop.swingx.JXLabel();
        lbl_qty = new org.jdesktop.swingx.JXLabel();
        lbl_at = new org.jdesktop.swingx.JXLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_price.setBackground(new java.awt.Color(255, 255, 255));
        lbl_price.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true)));
        lbl_price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_price.setText("100.00");
        lbl_price.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_price.setOpaque(true);
        lbl_price.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_priceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_priceMouseExited(evt);
            }
        });
        getContentPane().add(lbl_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 90, 50));

        lbl_desc.setBackground(new java.awt.Color(255, 255, 255));
        lbl_desc.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true)));
        lbl_desc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_desc.setText("1 pc Chicken with Rice and Egg");
        lbl_desc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_desc.setOpaque(true);
        lbl_desc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_descMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_descMouseExited(evt);
            }
        });
        getContentPane().add(lbl_desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 260, 50));

        lbl_qty.setBackground(new java.awt.Color(255, 255, 255));
        lbl_qty.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true)));
        lbl_qty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_qty.setText("50");
        lbl_qty.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_qty.setOpaque(true);
        lbl_qty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_qtyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_qtyMouseExited(evt);
            }
        });
        getContentPane().add(lbl_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        lbl_at.setBackground(new java.awt.Color(255, 255, 255));
        lbl_at.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_at.setText("@");
        lbl_at.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_at.setOpaque(true);
        lbl_at.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_atMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_atMouseExited(evt);
            }
        });
        getContentPane().add(lbl_at, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 20, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_descMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_descMouseEntered
        highlight();
    }//GEN-LAST:event_lbl_descMouseEntered

    private void lbl_descMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_descMouseExited
        darken();
    }//GEN-LAST:event_lbl_descMouseExited

    private void lbl_qtyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_qtyMouseEntered
        highlight();
    }//GEN-LAST:event_lbl_qtyMouseEntered

    private void lbl_atMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_atMouseEntered
        highlight();
    }//GEN-LAST:event_lbl_atMouseEntered

    private void lbl_priceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_priceMouseEntered
        highlight();
    }//GEN-LAST:event_lbl_priceMouseEntered

    private void lbl_priceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_priceMouseExited
        darken();
    }//GEN-LAST:event_lbl_priceMouseExited

    private void lbl_atMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_atMouseExited
        darken();
    }//GEN-LAST:event_lbl_atMouseExited

    private void lbl_qtyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_qtyMouseExited
        darken();
    }//GEN-LAST:event_lbl_qtyMouseExited
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXLabel lbl_at;
    private org.jdesktop.swingx.JXLabel lbl_desc;
    private org.jdesktop.swingx.JXLabel lbl_price;
    private org.jdesktop.swingx.JXLabel lbl_qty;
    // End of variables declaration//GEN-END:variables

    private void myInit() {
        init_key();
    }

    public void do_pass() {
    }
    // <editor-fold defaultstate="collapsed" desc="Key">

    private void disposed() {
        this.dispose();
    }

    private void init_key() {
        KeyMapping.mapKeyWIFW(getSurface(),
                KeyEvent.VK_ESCAPE, new KeyAction() {

            @Override
            public void actionPerformed(ActionEvent e) {
//                btn_0.doClick();
                disposed();
            }
        });
    }
    // </editor-fold>

    private void highlight() {
        lbl_desc.setBackground(new java.awt.Color(153, 204, 255));
        lbl_qty.setBackground(new java.awt.Color(153, 204, 255));
        lbl_at.setBackground(new java.awt.Color(153, 204, 255));
        lbl_price.setBackground(new java.awt.Color(153, 204, 255));
        lbl_desc.setForeground(new java.awt.Color(255, 255, 255));
    }

    private void darken() {
        lbl_desc.setBackground(new java.awt.Color(255, 255, 255));
        lbl_qty.setBackground(new java.awt.Color(255, 255, 255));
        lbl_at.setBackground(new java.awt.Color(255, 255, 255));
        lbl_price.setBackground(new java.awt.Color(255, 255, 255));
        lbl_desc.setForeground(new java.awt.Color(0, 0, 0));
    }
}
